// DEFINING THE ACTIONS FOR THE DISPATCH FUNCTION
export const ACTIONS = {
  ADD_DIGITS: "ADD_DIGITS",
  CLEAR: "CLEAR",
  BACKSPACE: "BACKSPACE",
  CALCULATE: "CALCULATE",
  OPERATION: "OPERATION",
  COMBINED: "COMBINED",
};
